export const ESTILOS = {
  container: {
    fontFamily: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    padding: "20px",
    maxWidth: "1280px",
    margin: "0 auto",
    backgroundColor: "#f1f5f9",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    textAlign: "center",
    marginBottom: "20px",
    color: "#1e293b",
    borderBottom: "2px solid #cbd5e1",
    paddingBottom: "10px",
  },
  menu: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  btnMenu: (ativo) => ({
    padding: "12px 25px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    backgroundColor: ativo ? "#2563eb" : "#ffffff",
    color: ativo ? "white" : "#64748b",
    fontWeight: "bold",
    fontSize: "14px",
    boxShadow: "0 2px 5px rgba(0,0,0,0.05)",
    transition: "0.2s",
  }),
  card: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "25px",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
    border: "1px solid #e2e8f0",
    flex: 1,
  },
  controlBar: {
    display: "flex",
    gap: "15px",
    alignItems: "center",
    marginBottom: "20px",
    padding: "15px",
    backgroundColor: "#f8fafc",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    flexWrap: "wrap",
  },
  input: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    fontSize: "14px",
  },
  btnAcao: {
    padding: "8px 16px",
    backgroundColor: "#16a34a",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "14px",
  },
  btnPDF: {
    padding: "10px 20px",
    backgroundColor: "#2563eb",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  btnLimpar: {
    padding: "10px 20px",
    backgroundColor: "#dc2626",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
  },
  turmaTag: (cor, ativa) => ({
    backgroundColor: cor,
    color: "white",
    padding: "6px 12px",
    border: ativa ? "3px solid #1e293b" : "3px solid transparent",
    borderRadius: "20px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "bold",
    boxShadow: "0 1px 2px rgba(0,0,0,0.1)",
  }),
  aviso: {
    backgroundColor: "#eff6ff",
    color: "#1e40af",
    padding: "12px",
    borderRadius: "8px",
    marginBottom: "15px",
    borderLeft: "4px solid #3b82f6",
    fontSize: "14px",
  },
  tabelaContainer: {
    marginTop: "30px",
    display: "grid",
    gridTemplateColumns: "1.5fr 1fr",
    gap: "30px",
  },
  tabela: { width: "100%", borderCollapse: "collapse", fontSize: "13px" },
  th: {
    backgroundColor: "#f1f5f9",
    padding: "10px",
    textAlign: "left",
    borderBottom: "2px solid #cbd5e1",
    color: "#475569",
  },
  td: { padding: "8px", borderBottom: "1px solid #e2e8f0", color: "#334155" },
  footer: {
    textAlign: "center",
    marginTop: "40px",
    paddingTop: "20px",
    borderTop: "1px solid #e2e8f0",
    color: "#94a3b8",
    fontSize: "12px",
  },
  // --- NOVOS ESTILOS PARA AJUDA/MODAL ---
  btnAjuda: {
    padding: "6px 12px",
    backgroundColor: "#64748b",
    color: "white",
    border: "none",
    borderRadius: "20px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "12px",
    marginLeft: "15px",
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "white",
    padding: "30px",
    borderRadius: "12px",
    maxWidth: "650px",
    width: "90%",
    maxHeight: "85vh",
    overflowY: "auto",
    boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
    position: "relative",
  },
  modalClose: {
    position: "absolute",
    top: "15px",
    right: "15px",
    border: "none",
    background: "transparent",
    fontSize: "20px",
    cursor: "pointer",
    fontWeight: "bold",
    color: "#64748b",
  },
  tituloAjuda: {
    color: "#1e293b",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: "10px",
    marginTop: 0,
  },
};

export const CORES_TURMAS = [
  "#2563eb",
  "#059669",
  "#7c3aed",
  "#d97706",
  "#db2777",
  "#0891b2",
  "#dc2626",
];
